### ISSUE TITLE
Config file not found as of prettier 3.1.1

### ISSUE THREAD

**Issue by RedHatter** [skrtheboss/prettier-tools#157]
After upgrading to prettier 3.1.1 the following does not find the config file.
```
pretty-parallel  --write ./
```
Works fine if I pass the path directly
```
pretty-parallel --config ./.prettierrc  --write ./
```

**Comment by skrtheboss** [comment]
Hi @RedHatter, sorry for the late response.

Should be fixed in 1.0.2 :smile:
